"""
Scenario data for Lab 02.  DO NOT EDIT THIS FILE.

Each scenario is one Diffie-Hellman key exchange that you have eavesdropped on.
You know the public values only:

    g   the generator
    n   the modulus
    A   Alice's public value, g^a mod n
    B   Bob's public value,   g^b mod n

Your job (in skeleton.py) is to recover the shared key g^(ab) mod n when the
parameters allow it.  Use check(scenario_id, key) to test a candidate key; it
compares a hash, so nothing in this file tells you the answer.
"""

import hashlib
from dataclasses import dataclass


@dataclass(frozen=True)
class Scenario:
    id: int
    g: int
    n: int
    A: int
    B: int


SCENARIOS: list[Scenario] = [
    Scenario(id=1, g=5, n=23,
             A=19,
             B=17),
    Scenario(id=2, g=3872211015087583665, n=9963569738995424389,
             A=3872211015087583665,
             B=3872211015087583665),
    Scenario(id=3, g=986497477413295558, n=9963569738995424389,
             A=2996317089639281241,
             B=862962412697826691),
    Scenario(id=4, g=2820412806683018284, n=12241706495108194253,
             A=672792490062124985,
             B=9718822233240708255),
    Scenario(id=5, g=4843882187754654320, n=14350815840562335419,
             A=6000893283917299639,
             B=4478146194104466743),
    Scenario(id=6, g=14350815840562335418, n=14350815840562335419,
             A=14350815840562335418,
             B=14350815840562335418),
    Scenario(id=7, g=4449417890543298275, n=6347288228911099741,
             A=4539918062210705238,
             B=5406819982132562460),
    Scenario(id=8, g=589308446324040562, n=6347288228911099741,
             A=2373999266000099814,
             B=4749674779248432677),
    Scenario(id=9, g=1380889579903879951, n=12241706495108194253,
             A=5697403814009845641,
             B=10857110447958648793),
]

_KEY_HASHES: dict[int, str] = {
    1: "e629fa6598d732768f7c726b4b621285f9c3b85303900aa912017db7617d8bdb",
    2: "e43e4bea331e73bccfe85540770a29829742549700bba5ad4f233609cd7e5d3b",
    3: "bf088741a463dbc87ccad7d4f9784d063b6b75408bcc35e7d802420b31098c50",
    4: "cb75335b9925cddc92227db2bf82be5c3e671fbb2dd15d80a215febd8aaaa3a3",
    5: "b3c14b4bd8f20736425c97a68baf7758f184dd465cb00637afe5d0d2f0c1028e",
    6: "74602562b88b12884e1c3adddf35a108b95ec04d86884b4786676febcdfec3d4",
    7: "0de862a8734ce0bbdb0f1b861c31b709df7f798d071290f1961450af7d18962b",
    8: "abef5b4a7bcd968cc7562a7b29c3bca8d5a50934304b44b854351439d27904ff",
    9: "f2834ff4008e53681a7fa907ad4ac9447a6edc4792f0867ee854c674b45202f2",
}


def get_scenarios() -> list[Scenario]:
    """All scenarios, in display order."""
    return list(SCENARIOS)


def check(scenario_id: int, key: int) -> bool:
    """True if `key` is the shared key for the given scenario."""
    digest = hashlib.sha256(str(int(key)).encode()).hexdigest()
    return _KEY_HASHES.get(scenario_id) == digest
