"""
Lab 02, Part 1: Brute-forcing Diffie-Hellman

You have eavesdropped on nine Diffie-Hellman key exchanges.  For each one you
know the public values g, n, A = g^a mod n and B = g^b mod n, and nothing else.
Recover the shared key g^(ab) mod n by brute force wherever that is fast enough,
and say "cannot determine" otherwise.  Scenario 1 is small enough to work by
hand; do that first, then check that your code agrees.

Run with:

    python3 skeleton_brute_force.py

Edit only this file.  scenarios.py supplies the data and a hash-based checker.
"""

from __future__ import annotations

import time

import scenarios
from scenarios import Scenario

# Give up on a scenario after this many candidate exponents.
LIMIT = 2_000_000


def attack(s: Scenario) -> int | None:
    """
    Return the shared key g^(ab) mod n, or None if brute force cannot find it
    within LIMIT steps.

    The idea: try a = 0, 1, 2, 3, ... until g^a mod n equals A.  Then the
    shared key is B^a mod n.

    Two things to think about:
      * You do not need fast modular exponentiation for the search.  Each
        candidate g^a is the previous one times g, reduced mod n.  Keep a
        running product instead of recomputing the power from scratch.
      * When you find a, it may not be Alice's actual secret exponent, only
        the smallest exponent that produces A.  Why is that still enough to
        get the right key?  (Hint: B lies in the subgroup generated by g.)

    Once a is found, computing B^a mod n does call for exponentiation.  Python's
    built-in pow(B, a, n) is fine, or reuse your fast_mod from Lab 01.
    """
    return None


def main() -> None:
    solved = 0
    total_start = time.perf_counter()
    for s in scenarios.get_scenarios():
        start = time.perf_counter()
        key = attack(s)
        elapsed = time.perf_counter() - start
        if key is None:
            print(f"Scenario {s.id}: cannot determine            ({elapsed:.2f} s)")
        elif scenarios.check(s.id, key):
            solved += 1
            print(f"Scenario {s.id}: key = {key:<20} PASSED ({elapsed:.2f} s)")
        else:
            print(f"Scenario {s.id}: key = {key:<20} FAILED ({elapsed:.2f} s)")
    total = time.perf_counter() - total_start
    print(f"\nRecovered {solved} of {len(scenarios.SCENARIOS)} keys in {total:.2f} s")


main()
